In [1]:
import numpy as np
import pandas as pd

In [2]:
#1--- CREATION OF DATAFRAMES

In [4]:
#Using dictionary
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
#Using 2D list
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
col=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=col) #By only giving list the columns name would be 0,1..
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
#2--- SELECTION AND INDEXING OF COLUMNS

In [8]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [9]:
df2[['Name','City']] #selecting 2 cols

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [10]:
#3--- CREATING NEW COLUMNS

In [18]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Teacher"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000     Teacher

In [13]:
#4--- REMOVING A COLUMN

In [19]:
df2.drop('Designation',axis=1) #col hata rhe isliye axis=1
#Now this will create a copy of the og dataset to remove designation from original we will use "implace"

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000     Teacher

In [16]:
df2.drop('Designation',axis=1, inplace=True)
#we can drop more than one columns by giving in list
#.drop(['Name','Age']) aise

In [17]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#5--- SELECTING ROWS(loc)

In [22]:
df2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [24]:
df2.loc[[0,2]]

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
2  Peter   29    Berlin   62000      Doctor

In [25]:
#We can also use iloc which takes the index value to select 
df2.iloc[3]

Name             Linda
Age                 42
City            London
Salary           85000
Designation    Teacher
Name: 3, dtype: object

In [26]:
#6--- SELECTING SUBSETS OF ROWS AND COLUMNS

In [27]:
df2.loc[[0,1]][["City","Salary"]]
#loc se pehle row select kari phir columns to hum name se select kar hi lete hain

       City  Salary
0  New York   65000
1     Paris   70000

In [30]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [31]:
#7--- CONDITIONAL SELECTION

In [32]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000     Teacher

In [33]:
#I want to people with age above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000     Teacher

In [36]:
# Want people with age above 30 and lives in Paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000        Eng.