In [1]:
#1--- FINDING MISSING DATA

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum() #sum se hum count nikal sakte hain null value ka

A    1
B    0
C    2
D    3
dtype: int64

In [11]:
df.isna().any() #atleast one null value ho

A     True
B    False
C     True
D     True
dtype: bool

In [14]:
#2--- REMOVING NULL VALUES (Works with rows)

In [16]:
df.dropna() #all rows having atleast one null will be dropped

     A  B    C    D
0  1.0  1  1.0  1.0

In [17]:
df.dropna(thresh=3) #drop rows having atleast 3 not null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [18]:
#3--- FILLING THE MISSING VALUES

In [19]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [5]:
#FILLING WITH SPECIFIC VALUE
values={'A':0,'B':100,'C':300,'D':400}  
df.fillna(value=values) #Works column wise

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [6]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
#FILLING WITH MEAN

In [8]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0